GET https://jsonplaceholder.typicode.com/posts;


###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "Islom JR",
    "Year": "2003",
    "Job": "Frontend Developer"
}